env: "local" # Environment - local, dev or prod
storage_path: "./storage/storage.db" # the file in which our database will be stored
http_server: # configuration of our http server
    address: "localhost:8082"
    timeout: 4s
    idle_timeout: 30s